In [1]:
import numpy as np
import pandas as pd

In [1]:
4.39	1.59	4.54,
3.82	1.82	3.99,
7.66	2.95	7.29,
7.95	2.55	7.22,
1.87	0.68	2.50,
4.90	1.97	5.38,
4.46	2.30	5.07,
6.46	2.28	5.65,
7.09	2.71	6.41,
7.55	2.49	6.52,

SyntaxError: invalid syntax. Perhaps you forgot a comma? (Temp/ipykernel_9188/3981118302.py, line 1)

In [2]:
a = np.array([4.39,
              3.82,
              7.66,
              7.95,
              1.87,
              4.90,
              4.46,
              6.46,
              7.09,
              7.55])


In [3]:
b = np.array([1.59,
1.82,
2.95,
2.55,
0.68,
1.97,
2.30,
2.28,
2.71,
2.49])

In [4]:
c = np.array([4.54,
3.99,
7.29,
7.22,
2.50,
5.38,
5.07,
5.65,
6.41,
6.52,])

In [7]:
data = pd.DataFrame()
data[0] = a
data[1] = b
data[2] = c


In [8]:
data

0     1     2
0  4.39  1.59  4.54
1  3.82  1.82  3.99
2  7.66  2.95  7.29
3  7.95  2.55  7.22
4  1.87  0.68  2.50
5  4.90  1.97  5.38
6  4.46  2.30  5.07
7  6.46  2.28  5.65
8  7.09  2.71  6.41
9  7.55  2.49  6.52

In [11]:
dataAd =pd.DataFrame()
dataAd[0] = list(data[0])- data[0].mean()
dataAd[1] = list(data[1])- data[1].mean()
dataAd[2] = list(data[2])- data[2].mean()

In [13]:
data

0     1     2
0  4.39  1.59  4.54
1  3.82  1.82  3.99
2  7.66  2.95  7.29
3  7.95  2.55  7.22
4  1.87  0.68  2.50
5  4.90  1.97  5.38
6  4.46  2.30  5.07
7  6.46  2.28  5.65
8  7.09  2.71  6.41
9  7.55  2.49  6.52

In [15]:
dataAd.cov()

0         1         2
0  4.095672  1.211411  2.980372
1  1.211411  0.431316  0.932447
2  2.980372  0.932447  2.270668

In [14]:
data[0].mean()

5.615

In [20]:
h,j = np.linalg.eig(dataAd.cov())

In [26]:
h[0]/j[:][0].sum()

-4.175809810218673

In [25]:
h[1]/j[1].sum()

-0.2606675381258404

In [24]:
h[2]/j[2].sum()

0.05766000926239808

In [21]:
h

array([6.67430999, 0.09048126, 0.03286431])

In [33]:
j.round(2)

array([[-0.78, -0.58, -0.24],
       [-0.24,  0.63, -0.74],
       [-0.58,  0.52,  0.63]])

array([-0.78028542, -0.57718529, -0.24085639])

In [32]:
for i in range(3):
    for q in range(3):
        print(h[i]/np.array(j[q][i]).sum())

    break

-8.55367767726259
-28.066241046636357
-11.538287682777536
